application: the-pppyo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# - url: /font-awesome-4.1./css
#   static_dir: /font-awesome-4.1./css

- url: /favicon\.ico
  static_files: onepage/favicon.ico
  upload: onepage/favicon\.ico

- url: /fonts
  static_dir: onepage/fonts

- url: /css
  static_dir: onepage/css

- url: /js
  static_dir: onepage/js

- url: /img
  static_dir: onepage/img

- url: /.*
  script: pppyo.app

libraries:
- name: webapp2
  version: latest
- name: django
  version: latest